"""changed the menu column image.

Revision ID: 7aae19969427
Revises: ec6d1279389f
Create Date: 2023-10-06 13:02:35.594701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aae19969427'
down_revision = 'ec6d1279389f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))
       

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.drop_column(sa.Column('image_data', sa.BLOB(), nullable=True))
        batch_op.drop_column('image_data')
        

    # ### end Alembic commands ###
