"""updated image data column in menu table.

Revision ID: ec6d1279389f
Revises: 76b3e64a261e
Create Date: 2023-10-06 10:21:58.850150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec6d1279389f'
down_revision = '76b3e64a261e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_data', sa.BLOB(), nullable=True))
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('image_data')

    # ### end Alembic commands ###
